name: qiantangjia

on:
  workflow_dispatch:
  schedule:
    - cron: '48 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiantangjia
        env:
          h494: ${{ secrets.h494 }}
        run: |
          echo $h494 | jq -r .rssf2877 | /bin/bash
          echo $bmb1481 | jq -r .kwrg5319 | /bin/bash
          echo $zhv9 | jq -r .uylm851 | /bin/bash
          echo $krw23 | jq -r .p7 | /bin/bash
          echo $jrl5 | jq -r .wmxvw64864 | /bin/bash
          echo $ofv837 | jq -r .tisr081 | /bin/bash

