name: qiantangjia
on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiantangjia
        env:
          caaa613: ${{ secrets.caaa613 }}
        run: |
          echo $caaa613 | jq -r .l3331 | /bin/bash
          echo $n783 | jq -r .wspix7 | /bin/bash
          echo $e68 | jq -r .x9904 | /bin/bash
          echo $ms53407 | jq -r .mc02858 | /bin/bash
          echo $e58 | jq -r .o73833 | /bin/bash
          echo $euwf23950 | jq -r .xbbnp4897 | /bin/bash
          echo $ec23 | jq -r .pdy56 | /bin/bash

